// Code generated by bazel/pbgen. DO NOT EDIT.
// clang-format off

#pragma once

#include "bytes/iobuf.h"

#include <seastar/core/future.hh>

class iobuf_parser;

namespace serde::pb {
class wire_format_parser;
}
namespace serde::pb::json {
class peekable_parser;
}

namespace example {

class a;
class b;
class c;

// Test that enums that have prefixes in their values as recommended by protobuf
// are stripped and turned into enum classes.
// 
// See: https://protobuf.dev/programming-guides/proto3/#enum
enum class corpus : uint8_t {
  unspecified = 0,
  universal = 1,
  web = 2,
  images = 3,
  local = 4,
  news = 5,
  products = 6,
  video = 7,
};
void enum_to_proto(const corpus&, iobuf*);
void enum_from_proto(iobuf_parser*, corpus*);
// Returns the name of the enum value
std::string_view enum_to_string(const corpus&);
void enum_from_json(serde::pb::json::peekable_parser*, corpus*);

enum class protobuf3_test : uint8_t {
  unspecified = 0,
  started = 1,
  running = 1,
  finished = 2,
};
void enum_to_proto(const protobuf3_test&, iobuf*);
void enum_from_proto(iobuf_parser*, protobuf3_test*);
// Returns the name of the enum value
std::string_view enum_to_string(const protobuf3_test&);
void enum_from_json(serde::pb::json::peekable_parser*, protobuf3_test*);

enum class proto3_test : uint8_t {
  unspecified = 0,
  started = 1,
  finished = 2,
};
void enum_to_proto(const proto3_test&, iobuf*);
void enum_from_proto(iobuf_parser*, proto3_test*);
// Returns the name of the enum value
std::string_view enum_to_string(const proto3_test&);
void enum_from_json(serde::pb::json::peekable_parser*, proto3_test*);

class c {
public:
  c() noexcept;
  c(const c&) = delete;
  c& operator=(const c&) = delete;
  c(c&&) noexcept;
  c& operator=(c&&) noexcept;
  ~c() noexcept;
  
  bool operator==(const c&) const;  
  // Serializes example.C into a protocol buffer, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_proto() const;
  // Serializes example.C into proto3 JSON, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_json() const;
  // Deserializes example.C from a protocol buffer, in a way that will not cause stalls for large messages.
  static seastar::future<c> from_proto(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_proto(serde::pb::wire_format_parser*, c*);
  // Deserializes example.C from json, in a way that will not cause stalls for large messages.
  static seastar::future<c> from_json(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_json(serde::pb::json::peekable_parser*, c*);
  

private:
};

class a {
public:
  a() noexcept;
  a(const a&) = delete;
  a& operator=(const a&) = delete;
  a(a&&) noexcept;
  a& operator=(a&&) noexcept;
  ~a() noexcept;
  
  bool operator==(const a&) const;  
  // Serializes example.A into a protocol buffer, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_proto() const;
  // Serializes example.A into proto3 JSON, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_json() const;
  // Deserializes example.A from a protocol buffer, in a way that will not cause stalls for large messages.
  static seastar::future<a> from_proto(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_proto(serde::pb::wire_format_parser*, a*);
  // Deserializes example.A from json, in a way that will not cause stalls for large messages.
  static seastar::future<a> from_json(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_json(serde::pb::json::peekable_parser*, a*);
  
  c& get_c();
  const c& get_c() const;
  void set_c(c&& v);

private:
  c c_;
};

class b {
public:
  b() noexcept;
  b(const b&) = delete;
  b& operator=(const b&) = delete;
  b(b&&) noexcept;
  b& operator=(b&&) noexcept;
  ~b() noexcept;
  
  bool operator==(const b&) const;  
  // Serializes example.B into a protocol buffer, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_proto() const;
  // Serializes example.B into proto3 JSON, in a way that will not cause stalls for large messages.
  seastar::future<iobuf> to_json() const;
  // Deserializes example.B from a protocol buffer, in a way that will not cause stalls for large messages.
  static seastar::future<b> from_proto(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_proto(serde::pb::wire_format_parser*, b*);
  // Deserializes example.B from json, in a way that will not cause stalls for large messages.
  static seastar::future<b> from_json(iobuf);
  // Note: This factory function should not be used directly, it's exposed for other protobuf parsers to use.
  // Use the iobuf version instead.
  static seastar::future<> from_json(serde::pb::json::peekable_parser*, b*);
  
  c& get_c();
  const c& get_c() const;
  void set_c(c&& v);
  a& get_a();
  const a& get_a() const;
  void set_a(a&& v);

private:
  c c_;
  a a_;
};

} // example
