// Code generated by bazel/pbgen. DO NOT EDIT.
// clang-format off
// NOLINTBEGIN(*-avoid-magic-numbers)

#include "src/v/serde/protobuf/tests/codegen_test.proto.h"

#include "bytes/iobuf_parser.h"
#include "serde/protobuf/wire_format.h"
#include "serde/protobuf/support.h"
#include "serde/protobuf/json.h"
#include "serde/json/writer.h"
#include "serde/json/parser.h"

#include <algorithm>
#include <fmt/format.h>
#include <seastar/coroutine/maybe_yield.hh>

namespace example {

void enum_from_proto(iobuf_parser* p, corpus* e) {
  auto v = serde::pb::read_varint<int32_t, serde::pb::zigzag::no>(p);
  constexpr static auto values = std::to_array<int32_t>({
    0, // CORPUS_UNSPECIFIED
    1, // CORPUS_UNIVERSAL
    2, // CORPUS_WEB
    3, // CORPUS_IMAGES
    4, // CORPUS_LOCAL
    5, // CORPUS_NEWS
    6, // CORPUS_PRODUCTS
    7, // CORPUS_VIDEO
  });
  if (!std::ranges::contains(values, v)) {
    v = 0;
  }
  *e = static_cast<corpus>(v);
}
void enum_to_proto(const corpus& e, iobuf* buf) {
  serde::pb::write_varint<int32_t, serde::pb::zigzag::no>(static_cast<int32_t>(e), buf);
}
std::string_view enum_to_string(const corpus& e) {
  switch (e) {
  case corpus::corpus_unspecified:
    return "CORPUS_UNSPECIFIED";
  case corpus::corpus_universal:
    return "CORPUS_UNIVERSAL";
  case corpus::corpus_web:
    return "CORPUS_WEB";
  case corpus::corpus_images:
    return "CORPUS_IMAGES";
  case corpus::corpus_local:
    return "CORPUS_LOCAL";
  case corpus::corpus_news:
    return "CORPUS_NEWS";
  case corpus::corpus_products:
    return "CORPUS_PRODUCTS";
  case corpus::corpus_video:
    return "CORPUS_VIDEO";
  default:
    return "CORPUS_UNSPECIFIED";
  }
}
void enum_from_json(serde::pb::json::peekable_parser* p, corpus* e) {
  switch (p->token()) {
  case serde::json::token::value_string: {
    constexpr static auto values = std::to_array<std::pair<std::string_view, corpus>>({
      {"CORPUS_IMAGES", corpus::corpus_images},
      {"CORPUS_LOCAL", corpus::corpus_local},
      {"CORPUS_NEWS", corpus::corpus_news},
      {"CORPUS_PRODUCTS", corpus::corpus_products},
      {"CORPUS_UNIVERSAL", corpus::corpus_universal},
      {"CORPUS_UNSPECIFIED", corpus::corpus_unspecified},
      {"CORPUS_VIDEO", corpus::corpus_video},
      {"CORPUS_WEB", corpus::corpus_web},
    });
    auto eq = std::ranges::equal_range(values, p->value_string(), std::less<>(), [](const auto& pair) { return pair.first; });
    if (eq.empty()) {
      *e = corpus::corpus_unspecified;
    } else {
      *e = eq.front().second;
    }
    return;
  }
  case serde::json::token::value_int: {
    switch (p->value_int()) {
    case 0:
      *e = corpus::corpus_unspecified;
      return;
    case 1:
      *e = corpus::corpus_universal;
      return;
    case 2:
      *e = corpus::corpus_web;
      return;
    case 3:
      *e = corpus::corpus_images;
      return;
    case 4:
      *e = corpus::corpus_local;
      return;
    case 5:
      *e = corpus::corpus_news;
      return;
    case 6:
      *e = corpus::corpus_products;
      return;
    case 7:
      *e = corpus::corpus_video;
      return;
    default:
      *e = corpus::corpus_unspecified;
      return;
    }
  }
  default:
    throw std::runtime_error(fmt::format("unexpected json token for enum, got: {}", p->token()));
  }
}

void enum_from_proto(iobuf_parser* p, protobuf3_test* e) {
  auto v = serde::pb::read_varint<int32_t, serde::pb::zigzag::no>(p);
  constexpr static auto values = std::to_array<int32_t>({
    0, // PROTOBUF3_TEST_UNSPECIFIED
    1, // PROTOBUF3_TEST_STARTED
    1, // PROTOBUF3_TEST_RUNNING
    2, // PROTOBUF3_TEST_FINISHED
  });
  if (!std::ranges::contains(values, v)) {
    v = 0;
  }
  *e = static_cast<protobuf3_test>(v);
}
void enum_to_proto(const protobuf3_test& e, iobuf* buf) {
  serde::pb::write_varint<int32_t, serde::pb::zigzag::no>(static_cast<int32_t>(e), buf);
}
std::string_view enum_to_string(const protobuf3_test& e) {
  switch (e) {
  case protobuf3_test::protobuf3_test_unspecified:
    return "PROTOBUF3_TEST_UNSPECIFIED";
  case protobuf3_test::protobuf3_test_started:
    return "PROTOBUF3_TEST_STARTED";
  case protobuf3_test::protobuf3_test_running:
    return "PROTOBUF3_TEST_RUNNING";
  case protobuf3_test::protobuf3_test_finished:
    return "PROTOBUF3_TEST_FINISHED";
  default:
    return "PROTOBUF3_TEST_UNSPECIFIED";
  }
}
void enum_from_json(serde::pb::json::peekable_parser* p, protobuf3_test* e) {
  switch (p->token()) {
  case serde::json::token::value_string: {
    constexpr static auto values = std::to_array<std::pair<std::string_view, protobuf3_test>>({
      {"PROTOBUF3_TEST_FINISHED", protobuf3_test::protobuf3_test_finished},
      {"PROTOBUF3_TEST_RUNNING", protobuf3_test::protobuf3_test_running},
      {"PROTOBUF3_TEST_STARTED", protobuf3_test::protobuf3_test_started},
      {"PROTOBUF3_TEST_UNSPECIFIED", protobuf3_test::protobuf3_test_unspecified},
    });
    auto eq = std::ranges::equal_range(values, p->value_string(), std::less<>(), [](const auto& pair) { return pair.first; });
    if (eq.empty()) {
      *e = protobuf3_test::protobuf3_test_unspecified;
    } else {
      *e = eq.front().second;
    }
    return;
  }
  case serde::json::token::value_int: {
    switch (p->value_int()) {
    case 0:
      *e = protobuf3_test::protobuf3_test_unspecified;
      return;
    case 1:
      *e = protobuf3_test::protobuf3_test_started;
      return;
    case 1:
      *e = protobuf3_test::protobuf3_test_running;
      return;
    case 2:
      *e = protobuf3_test::protobuf3_test_finished;
      return;
    default:
      *e = protobuf3_test::protobuf3_test_unspecified;
      return;
    }
  }
  default:
    throw std::runtime_error(fmt::format("unexpected json token for enum, got: {}", p->token()));
  }
}

void enum_from_proto(iobuf_parser* p, proto3_test* e) {
  auto v = serde::pb::read_varint<int32_t, serde::pb::zigzag::no>(p);
  constexpr static auto values = std::to_array<int32_t>({
    0, // PROTO3_TEST_UNSPECIFIED
    1, // PROTO3_TEST_STARTED
    2, // PROTO3_TEST_FINISHED
  });
  if (!std::ranges::contains(values, v)) {
    v = 0;
  }
  *e = static_cast<proto3_test>(v);
}
void enum_to_proto(const proto3_test& e, iobuf* buf) {
  serde::pb::write_varint<int32_t, serde::pb::zigzag::no>(static_cast<int32_t>(e), buf);
}
std::string_view enum_to_string(const proto3_test& e) {
  switch (e) {
  case proto3_test::proto3_test_unspecified:
    return "PROTO3_TEST_UNSPECIFIED";
  case proto3_test::proto3_test_started:
    return "PROTO3_TEST_STARTED";
  case proto3_test::proto3_test_finished:
    return "PROTO3_TEST_FINISHED";
  default:
    return "PROTO3_TEST_UNSPECIFIED";
  }
}
void enum_from_json(serde::pb::json::peekable_parser* p, proto3_test* e) {
  switch (p->token()) {
  case serde::json::token::value_string: {
    constexpr static auto values = std::to_array<std::pair<std::string_view, proto3_test>>({
      {"PROTO3_TEST_FINISHED", proto3_test::proto3_test_finished},
      {"PROTO3_TEST_STARTED", proto3_test::proto3_test_started},
      {"PROTO3_TEST_UNSPECIFIED", proto3_test::proto3_test_unspecified},
    });
    auto eq = std::ranges::equal_range(values, p->value_string(), std::less<>(), [](const auto& pair) { return pair.first; });
    if (eq.empty()) {
      *e = proto3_test::proto3_test_unspecified;
    } else {
      *e = eq.front().second;
    }
    return;
  }
  case serde::json::token::value_int: {
    switch (p->value_int()) {
    case 0:
      *e = proto3_test::proto3_test_unspecified;
      return;
    case 1:
      *e = proto3_test::proto3_test_started;
      return;
    case 2:
      *e = proto3_test::proto3_test_finished;
      return;
    default:
      *e = proto3_test::proto3_test_unspecified;
      return;
    }
  }
  default:
    throw std::runtime_error(fmt::format("unexpected json token for enum, got: {}", p->token()));
  }
}

} // example
// NOLINTEND(*-avoid-magic-numbers)
