// Code generated by bazel/pbgen. DO NOT EDIT.
// clang-format off
// NOLINTBEGIN(*-avoid-magic-numbers)

#include "src/v/serde/protobuf/tests/codegen_test.proto.h"

#include "bytes/iobuf_parser.h"
#include "serde/protobuf/wire_format.h"
#include "serde/protobuf/support.h"
#include "serde/protobuf/json.h"
#include "serde/json/writer.h"
#include "serde/json/parser.h"

#include <algorithm>
#include <fmt/format.h>
#include <seastar/coroutine/maybe_yield.hh>

namespace example {

a::a() noexcept = default;
a::a(a&&) noexcept = default;
a& a::operator=(a&&) noexcept = default;
a::~a() noexcept = default;
bool a::operator==(const a&) const = default;
c& a::get_c() { return c_; }
const c& a::get_c() const { return c_; }
void a::set_c(c&& v) { c_ = std::move(v); }
seastar::future<> a::from_proto(serde::pb::wire_format_parser* parser, a* self) {
  while (parser->bytes_left() > 0) {
    auto tag = parser->read_tag();
    switch (tag.field_number) {
    case 1: { // c
      auto msg_parser = parser->read_message<"example.A.c">(tag);
      c sub_msg;
      co_await c::from_proto(&msg_parser, &sub_msg);
      self->set_c(std::move(sub_msg));
      break;
    }
    default:
      parser->skip_unknown(tag);
      break;
    }
  }
  co_return;
}
seastar::future<a> a::from_proto(iobuf buf) {
  a self;
  serde::pb::wire_format_parser parser{std::move(buf)};
  co_await from_proto(&parser, &self);
  parser.check_empty();
  co_return self;
}
seastar::future<iobuf> a::to_proto() const {
  iobuf buf;
  {
    // c
    serde::pb::tag::write({.wire_type = serde::pb::wire_type::length, .field_number = 1}, &buf);
    iobuf msg_buf = co_await get_c().to_proto();
    serde::pb::write_length(static_cast<int32_t>(msg_buf.size_bytes()), &buf);
    buf.append(std::move(msg_buf));
  }
  co_return buf;
}
seastar::future<iobuf> a::to_json() const {
  serde::json::writer w;
  w.begin_object();
  w.key("c");
  w.append_raw_json(co_await get_c().to_json());
  w.end_object();
  co_return std::move(w).finish();
}
seastar::future<> a::from_json(serde::pb::json::peekable_parser* parser, a* self) {
  constexpr static auto key_to_field_number = std::to_array<std::pair<std::string_view, int32_t>>({
    {"c", 1},
  });
  auto entries = serde::pb::json::object_key_generator(parser);
  while (auto key = co_await entries()) {
    auto fields = std::ranges::equal_range(key_to_field_number, *key, std::less<>(), [](const auto& pair) { return pair.first; });
    if (fields.empty()) {
      co_await parser->skip_value();
      continue;
    }
    switch (fields.front().second) {
    case 1: { // c
      if (co_await parser->peek() == serde::json::token::value_null) {
        co_await parser->next();
      } else {
        c v{};
        co_await c::from_json(parser, &v);
        self->set_c(std::move(v));
      }
      break;
    }
    default:
      vassert(false, "codegen error unexpected field number: {}", fields.front().second);
    }
  }
  co_return;
}
seastar::future<a> a::from_json(iobuf data) {
  a self;
  serde::pb::json::peekable_parser parser(std::move(data));
  co_await from_json(&parser, &self);
  co_await serde::pb::json::check_next_eof(&parser);
  co_return self;
}

b::b() noexcept = default;
b::b(b&&) noexcept = default;
b& b::operator=(b&&) noexcept = default;
b::~b() noexcept = default;
bool b::operator==(const b&) const = default;
c& b::get_c() { return c_; }
const c& b::get_c() const { return c_; }
void b::set_c(c&& v) { c_ = std::move(v); }
a& b::get_a() { return a_; }
const a& b::get_a() const { return a_; }
void b::set_a(a&& v) { a_ = std::move(v); }
seastar::future<> b::from_proto(serde::pb::wire_format_parser* parser, b* self) {
  while (parser->bytes_left() > 0) {
    auto tag = parser->read_tag();
    switch (tag.field_number) {
    case 1: { // c
      auto msg_parser = parser->read_message<"example.B.c">(tag);
      c sub_msg;
      co_await c::from_proto(&msg_parser, &sub_msg);
      self->set_c(std::move(sub_msg));
      break;
    }
    case 2: { // a
      auto msg_parser = parser->read_message<"example.B.a">(tag);
      a sub_msg;
      co_await a::from_proto(&msg_parser, &sub_msg);
      self->set_a(std::move(sub_msg));
      break;
    }
    default:
      parser->skip_unknown(tag);
      break;
    }
  }
  co_return;
}
seastar::future<b> b::from_proto(iobuf buf) {
  b self;
  serde::pb::wire_format_parser parser{std::move(buf)};
  co_await from_proto(&parser, &self);
  parser.check_empty();
  co_return self;
}
seastar::future<iobuf> b::to_proto() const {
  iobuf buf;
  {
    // c
    serde::pb::tag::write({.wire_type = serde::pb::wire_type::length, .field_number = 1}, &buf);
    iobuf msg_buf = co_await get_c().to_proto();
    serde::pb::write_length(static_cast<int32_t>(msg_buf.size_bytes()), &buf);
    buf.append(std::move(msg_buf));
  }
  {
    // a
    serde::pb::tag::write({.wire_type = serde::pb::wire_type::length, .field_number = 2}, &buf);
    iobuf msg_buf = co_await get_a().to_proto();
    serde::pb::write_length(static_cast<int32_t>(msg_buf.size_bytes()), &buf);
    buf.append(std::move(msg_buf));
  }
  co_return buf;
}
seastar::future<iobuf> b::to_json() const {
  serde::json::writer w;
  w.begin_object();
  w.key("c");
  w.append_raw_json(co_await get_c().to_json());
  w.key("a");
  w.append_raw_json(co_await get_a().to_json());
  w.end_object();
  co_return std::move(w).finish();
}
seastar::future<> b::from_json(serde::pb::json::peekable_parser* parser, b* self) {
  constexpr static auto key_to_field_number = std::to_array<std::pair<std::string_view, int32_t>>({
    {"a", 2},
    {"c", 1},
  });
  auto entries = serde::pb::json::object_key_generator(parser);
  while (auto key = co_await entries()) {
    auto fields = std::ranges::equal_range(key_to_field_number, *key, std::less<>(), [](const auto& pair) { return pair.first; });
    if (fields.empty()) {
      co_await parser->skip_value();
      continue;
    }
    switch (fields.front().second) {
    case 1: { // c
      if (co_await parser->peek() == serde::json::token::value_null) {
        co_await parser->next();
      } else {
        c v{};
        co_await c::from_json(parser, &v);
        self->set_c(std::move(v));
      }
      break;
    }
    case 2: { // a
      if (co_await parser->peek() == serde::json::token::value_null) {
        co_await parser->next();
      } else {
        a v{};
        co_await a::from_json(parser, &v);
        self->set_a(std::move(v));
      }
      break;
    }
    default:
      vassert(false, "codegen error unexpected field number: {}", fields.front().second);
    }
  }
  co_return;
}
seastar::future<b> b::from_json(iobuf data) {
  b self;
  serde::pb::json::peekable_parser parser(std::move(data));
  co_await from_json(&parser, &self);
  co_await serde::pb::json::check_next_eof(&parser);
  co_return self;
}

c::c() noexcept = default;
c::c(c&&) noexcept = default;
c& c::operator=(c&&) noexcept = default;
c::~c() noexcept = default;
bool c::operator==(const c&) const = default;
seastar::future<> c::from_proto(serde::pb::wire_format_parser* parser, c* self) {
  std::ignore = self;
  while (parser->bytes_left() > 0) {
    auto tag = parser->read_tag();
    switch (tag.field_number) {
    default:
      parser->skip_unknown(tag);
      break;
    }
  }
  co_return;
}
seastar::future<c> c::from_proto(iobuf buf) {
  c self;
  serde::pb::wire_format_parser parser{std::move(buf)};
  co_await from_proto(&parser, &self);
  parser.check_empty();
  co_return self;
}
seastar::future<iobuf> c::to_proto() const {
  iobuf buf;
  co_return buf;
}
seastar::future<iobuf> c::to_json() const {
  serde::json::writer w;
  w.begin_object();
  w.end_object();
  co_return std::move(w).finish();
}
seastar::future<> c::from_json(serde::pb::json::peekable_parser* parser, c* self) {
  std::ignore = self;
  constexpr static std::array<std::pair<std::string_view, int32_t>, 0> key_to_field_number = {};
  auto entries = serde::pb::json::object_key_generator(parser);
  while (auto key = co_await entries()) {
    auto fields = std::ranges::equal_range(key_to_field_number, *key, std::less<>(), [](const auto& pair) { return pair.first; });
    if (fields.empty()) {
      co_await parser->skip_value();
      continue;
    }
    switch (fields.front().second) {
    default:
      vassert(false, "codegen error unexpected field number: {}", fields.front().second);
    }
  }
  co_return;
}
seastar::future<c> c::from_json(iobuf data) {
  c self;
  serde::pb::json::peekable_parser parser(std::move(data));
  co_await from_json(&parser, &self);
  co_await serde::pb::json::check_next_eof(&parser);
  co_return self;
}

void enum_from_proto(iobuf_parser* p, corpus* e) {
  auto v = serde::pb::read_varint<int32_t, serde::pb::zigzag::no>(p);
  constexpr static auto values = std::to_array<int32_t>({
    0, // CORPUS_UNSPECIFIED
    1, // CORPUS_UNIVERSAL
    2, // CORPUS_WEB
    3, // CORPUS_IMAGES
    4, // CORPUS_LOCAL
    5, // CORPUS_NEWS
    6, // CORPUS_PRODUCTS
    7, // CORPUS_VIDEO
  });
  if (!std::ranges::contains(values, v)) {
    v = 0;
  }
  *e = static_cast<corpus>(v);
}
void enum_to_proto(const corpus& e, iobuf* buf) {
  serde::pb::write_varint<int32_t, serde::pb::zigzag::no>(static_cast<int32_t>(e), buf);
}
std::string_view enum_to_string(const corpus& e) {
  switch (e) {
  case corpus::unspecified:
    return "CORPUS_UNSPECIFIED";
  case corpus::universal:
    return "CORPUS_UNIVERSAL";
  case corpus::web:
    return "CORPUS_WEB";
  case corpus::images:
    return "CORPUS_IMAGES";
  case corpus::local:
    return "CORPUS_LOCAL";
  case corpus::news:
    return "CORPUS_NEWS";
  case corpus::products:
    return "CORPUS_PRODUCTS";
  case corpus::video:
    return "CORPUS_VIDEO";
  default:
    return "CORPUS_UNSPECIFIED";
  }
}
void enum_from_json(serde::pb::json::peekable_parser* p, corpus* e) {
  switch (p->token()) {
  case serde::json::token::value_string: {
    constexpr static auto values = std::to_array<std::pair<std::string_view, corpus>>({
      {"CORPUS_IMAGES", corpus::images},
      {"CORPUS_LOCAL", corpus::local},
      {"CORPUS_NEWS", corpus::news},
      {"CORPUS_PRODUCTS", corpus::products},
      {"CORPUS_UNIVERSAL", corpus::universal},
      {"CORPUS_UNSPECIFIED", corpus::unspecified},
      {"CORPUS_VIDEO", corpus::video},
      {"CORPUS_WEB", corpus::web},
    });
    auto eq = std::ranges::equal_range(values, p->value_string(), std::less<>(), [](const auto& pair) { return pair.first; });
    if (eq.empty()) {
      *e = corpus::unspecified;
    } else {
      *e = eq.front().second;
    }
    return;
  }
  case serde::json::token::value_int: {
    switch (p->value_int()) {
    case 0:
      *e = corpus::unspecified;
      return;
    case 1:
      *e = corpus::universal;
      return;
    case 2:
      *e = corpus::web;
      return;
    case 3:
      *e = corpus::images;
      return;
    case 4:
      *e = corpus::local;
      return;
    case 5:
      *e = corpus::news;
      return;
    case 6:
      *e = corpus::products;
      return;
    case 7:
      *e = corpus::video;
      return;
    default:
      *e = corpus::unspecified;
      return;
    }
  }
  default:
    throw std::runtime_error(fmt::format("unexpected json token for enum, got: {}", p->token()));
  }
}

void enum_from_proto(iobuf_parser* p, protobuf3_test* e) {
  auto v = serde::pb::read_varint<int32_t, serde::pb::zigzag::no>(p);
  constexpr static auto values = std::to_array<int32_t>({
    0, // PROTOBUF3_TEST_UNSPECIFIED
    1, // PROTOBUF3_TEST_STARTED
    1, // PROTOBUF3_TEST_RUNNING
    2, // PROTOBUF3_TEST_FINISHED
  });
  if (!std::ranges::contains(values, v)) {
    v = 0;
  }
  *e = static_cast<protobuf3_test>(v);
}
void enum_to_proto(const protobuf3_test& e, iobuf* buf) {
  serde::pb::write_varint<int32_t, serde::pb::zigzag::no>(static_cast<int32_t>(e), buf);
}
std::string_view enum_to_string(const protobuf3_test& e) {
  switch (e) {
  case protobuf3_test::unspecified:
    return "PROTOBUF3_TEST_UNSPECIFIED";
  case protobuf3_test::started:
    return "PROTOBUF3_TEST_STARTED";
  case protobuf3_test::finished:
    return "PROTOBUF3_TEST_FINISHED";
  default:
    return "PROTOBUF3_TEST_UNSPECIFIED";
  }
}
void enum_from_json(serde::pb::json::peekable_parser* p, protobuf3_test* e) {
  switch (p->token()) {
  case serde::json::token::value_string: {
    constexpr static auto values = std::to_array<std::pair<std::string_view, protobuf3_test>>({
      {"PROTOBUF3_TEST_FINISHED", protobuf3_test::finished},
      {"PROTOBUF3_TEST_STARTED", protobuf3_test::started},
      {"PROTOBUF3_TEST_UNSPECIFIED", protobuf3_test::unspecified},
    });
    auto eq = std::ranges::equal_range(values, p->value_string(), std::less<>(), [](const auto& pair) { return pair.first; });
    if (eq.empty()) {
      *e = protobuf3_test::unspecified;
    } else {
      *e = eq.front().second;
    }
    return;
  }
  case serde::json::token::value_int: {
    switch (p->value_int()) {
    case 0:
      *e = protobuf3_test::unspecified;
      return;
    case 1:
      *e = protobuf3_test::started;
      return;
    case 2:
      *e = protobuf3_test::finished;
      return;
    default:
      *e = protobuf3_test::unspecified;
      return;
    }
  }
  default:
    throw std::runtime_error(fmt::format("unexpected json token for enum, got: {}", p->token()));
  }
}

void enum_from_proto(iobuf_parser* p, proto3_test* e) {
  auto v = serde::pb::read_varint<int32_t, serde::pb::zigzag::no>(p);
  constexpr static auto values = std::to_array<int32_t>({
    0, // PROTO3_TEST_UNSPECIFIED
    1, // PROTO3_TEST_STARTED
    2, // PROTO3_TEST_FINISHED
  });
  if (!std::ranges::contains(values, v)) {
    v = 0;
  }
  *e = static_cast<proto3_test>(v);
}
void enum_to_proto(const proto3_test& e, iobuf* buf) {
  serde::pb::write_varint<int32_t, serde::pb::zigzag::no>(static_cast<int32_t>(e), buf);
}
std::string_view enum_to_string(const proto3_test& e) {
  switch (e) {
  case proto3_test::unspecified:
    return "PROTO3_TEST_UNSPECIFIED";
  case proto3_test::started:
    return "PROTO3_TEST_STARTED";
  case proto3_test::finished:
    return "PROTO3_TEST_FINISHED";
  default:
    return "PROTO3_TEST_UNSPECIFIED";
  }
}
void enum_from_json(serde::pb::json::peekable_parser* p, proto3_test* e) {
  switch (p->token()) {
  case serde::json::token::value_string: {
    constexpr static auto values = std::to_array<std::pair<std::string_view, proto3_test>>({
      {"PROTO3_TEST_FINISHED", proto3_test::finished},
      {"PROTO3_TEST_STARTED", proto3_test::started},
      {"PROTO3_TEST_UNSPECIFIED", proto3_test::unspecified},
    });
    auto eq = std::ranges::equal_range(values, p->value_string(), std::less<>(), [](const auto& pair) { return pair.first; });
    if (eq.empty()) {
      *e = proto3_test::unspecified;
    } else {
      *e = eq.front().second;
    }
    return;
  }
  case serde::json::token::value_int: {
    switch (p->value_int()) {
    case 0:
      *e = proto3_test::unspecified;
      return;
    case 1:
      *e = proto3_test::started;
      return;
    case 2:
      *e = proto3_test::finished;
      return;
    default:
      *e = proto3_test::unspecified;
      return;
    }
  }
  default:
    throw std::runtime_error(fmt::format("unexpected json token for enum, got: {}", p->token()));
  }
}

} // example
// NOLINTEND(*-avoid-magic-numbers)
